In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\j-luc\appdata\local\programs\python\python311\lib\site-packages (2.0.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\j-luc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\j-luc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\j-luc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\j-luc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\j-luc\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

In [3]:
#Carregar o arquivo excel e colocar dentro de uma váriavel 
df = pd.read_excel('dados_produtos.xlsx')

In [4]:
df

,Nome do Produto,Valor do Produto,Valor no Cartão
0,Placa de Vídeo RTX 3060 Asus Dual O12G V2 NVID...,"R$ 2.199,99","R$ 2.743,32"
1,Placa de Vídeo RTX 3060 Ti 1-Click OC Galax NV...,"R$ 2.449,99","R$ 3.144,43"
2,Placa de Vídeo RX 6600 CLD 8G ASRock AMD Radeo...,"R$ 1.449,99","R$ 2.223,52"
3,Placa de Vídeo RX 6750 XT Mech 2X 12G OC MSI A...,"R$ 2.559,99","R$ 3.222,21"
4,Placa de Vídeo RTX 3060 Twin Edge OC Zotac Gam...,"R$ 2.279,99","R$ 2.666,66"
...,...,...,...
1300,"Placa de Vídeo Pny NVIDIA GeForce Quadro T600,...",Valor do produto não encontrado,NaN
1301,Placa de Vídeo MSI NVIDIA GeForce Gaming Z Tri...,Valor do produto não encontrado,NaN
1302,"Placa De Vídeo Galax, Geforce GTX 1660 Super 6...",Valor do produto não encontrado,NaN
1303,"Placa de Vídeo Pcwinmax NVIDIA GeForce GT 740,...",Valor do produto não encontrado,NaN
1304,"Acessório Lian Li Cabo PCI-E, 4.0, X16, Riser,...",Valor do produto não encontrado,NaN

In [5]:
# Fazer o Tratamento dos dados onde só quero pegar as Placas de Vídeo, visto que tem produtos misturados
produtos_placa_video = df[df['Nome do Produto'].str.startswith('Placa de Vídeo')]

In [6]:
produtos_placa_video

,Nome do Produto,Valor do Produto,Valor no Cartão
0,Placa de Vídeo RTX 3060 Asus Dual O12G V2 NVID...,"R$ 2.199,99","R$ 2.743,32"
1,Placa de Vídeo RTX 3060 Ti 1-Click OC Galax NV...,"R$ 2.449,99","R$ 3.144,43"
2,Placa de Vídeo RX 6600 CLD 8G ASRock AMD Radeo...,"R$ 1.449,99","R$ 2.223,52"
3,Placa de Vídeo RX 6750 XT Mech 2X 12G OC MSI A...,"R$ 2.559,99","R$ 3.222,21"
4,Placa de Vídeo RTX 3060 Twin Edge OC Zotac Gam...,"R$ 2.279,99","R$ 2.666,66"
...,...,...,...
1298,Placa de Vídeo Gigabyte NVIDIA GeForce RTX 308...,Valor do produto não encontrado,NaN
1299,Placa de Vídeo MSI NVIDIA GeForce Gaming X GTX...,Valor do produto não encontrado,NaN
1300,"Placa de Vídeo Pny NVIDIA GeForce Quadro T600,...",Valor do produto não encontrado,NaN
1301,Placa de Vídeo MSI NVIDIA GeForce Gaming Z Tri...,Valor do produto não encontrado,NaN
1303,"Placa de Vídeo Pcwinmax NVIDIA GeForce GT 740,...",Valor do produto não encontrado,NaN

In [7]:
produtos_placa_video.shape

(975, 3)

In [8]:
display(produtos_placa_video)

,Nome do Produto,Valor do Produto,Valor no Cartão
0,Placa de Vídeo RTX 3060 Asus Dual O12G V2 NVID...,"R$ 2.199,99","R$ 2.743,32"
1,Placa de Vídeo RTX 3060 Ti 1-Click OC Galax NV...,"R$ 2.449,99","R$ 3.144,43"
2,Placa de Vídeo RX 6600 CLD 8G ASRock AMD Radeo...,"R$ 1.449,99","R$ 2.223,52"
3,Placa de Vídeo RX 6750 XT Mech 2X 12G OC MSI A...,"R$ 2.559,99","R$ 3.222,21"
4,Placa de Vídeo RTX 3060 Twin Edge OC Zotac Gam...,"R$ 2.279,99","R$ 2.666,66"
...,...,...,...
1298,Placa de Vídeo Gigabyte NVIDIA GeForce RTX 308...,Valor do produto não encontrado,NaN
1299,Placa de Vídeo MSI NVIDIA GeForce Gaming X GTX...,Valor do produto não encontrado,NaN
1300,"Placa de Vídeo Pny NVIDIA GeForce Quadro T600,...",Valor do produto não encontrado,NaN
1301,Placa de Vídeo MSI NVIDIA GeForce Gaming Z Tri...,Valor do produto não encontrado,NaN
1303,"Placa de Vídeo Pcwinmax NVIDIA GeForce GT 740,...",Valor do produto não encontrado,NaN

In [9]:
# Verificar se todos os produtos são placa de vídeo
todos_sao_placa_video = produtos_placa_video['Nome do Produto'].str.startswith('Placa de Vídeo').all()

In [10]:
# Exibir o resultado
if todos_sao_placa_video:
    print("Todos os produtos são de Placa de Vídeo.")
else:
    print("Existem produtos que não são de Placa de Vídeo na variável produtos_placa_video.")

Todos os produtos são de Placa de Vídeo.

In [11]:
tratado = 'arquivo_tratado.xlsx'
caminho_arquivo = tratado  # O arquivo será salvo na pasta atual
produtos_placa_video.to_excel(caminho_arquivo, index=False)